/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderNumber = IDL.Text;
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const TicketStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'valid' : IDL.Null,
  'used' : IDL.Null,
  'refunded' : IDL.Null,
});
export const EventId = IDL.Text;
export const SecureToken = IDL.Text;
export const TicketId = IDL.Text;
export const TierId = IDL.Text;
export const Ticket = IDL.Record({
  'status' : TicketStatus,
  'eventId' : EventId,
  'secureToken' : SecureToken,
  'ticketId' : TicketId,
  'orderId' : OrderNumber,
  'ticketType' : TierId,
});
export const ConfirmPaymentResult = IDL.Record({
  'status' : OrderStatus,
  'tickets' : IDL.Vec(Ticket),
  'orderNumber' : OrderNumber,
});
export const ConfirmPaymentError = IDL.Variant({
  'alreadyPaid' : OrderNumber,
  'unknownOrder' : OrderNumber,
  'orderExpired' : OrderNumber,
});
export const Rupiah = IDL.Nat;
export const Timestamp = IDL.Int;
export const CreateOrderResult = IDL.Record({
  'total' : Rupiah,
  'paymentDeadline' : Timestamp,
  'serviceFee' : Rupiah,
  'orderNumber' : OrderNumber,
  'subtotal' : Rupiah,
});
export const CreateOrderError = IDL.Variant({
  'invalidInput' : IDL.Text,
  'unknownTier' : TierId,
  'insufficientStock' : IDL.Record({
    'requested' : IDL.Nat,
    'tierId' : TierId,
    'remaining' : IDL.Nat,
  }),
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const EventInfo = IDL.Record({
  'id' : EventId,
  'timezone' : IDL.Text,
  'venue' : IDL.Text,
  'tagline' : IDL.Text,
  'city' : IDL.Text,
  'date' : IDL.Text,
  'startsAt' : Timestamp,
  'name' : IDL.Text,
  'time' : IDL.Text,
});
export const CustomerInfo = IDL.Record({
  'whatsapp' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
});
export const OrderLine = IDL.Record({
  'tierId' : TierId,
  'tierName' : IDL.Text,
  'lineTotal' : Rupiah,
  'quantity' : IDL.Nat,
  'unitPrice' : Rupiah,
});
export const Order = IDL.Record({
  'status' : OrderStatus,
  'total' : Rupiah,
  'tickets' : IDL.Vec(Ticket),
  'customer' : CustomerInfo,
  'paymentDeadline' : Timestamp,
  'createdAt' : Timestamp,
  'lines' : IDL.Vec(OrderLine),
  'serviceFee' : Rupiah,
  'orderNumber' : OrderNumber,
  'subtotal' : Rupiah,
});
export const TicketTier = IDL.Record({
  'id' : TierId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'soldOut' : IDL.Bool,
  'remaining' : IDL.Nat,
  'capacity' : IDL.Nat,
  'price' : Rupiah,
});
export const ScanResult = IDL.Variant({
  'alreadyUsed' : IDL.Record({ 'ticketId' : TicketId, 'ticketType' : TierId }),
  'invalidTicket' : IDL.Null,
  'validTicket' : IDL.Record({ 'ticketId' : TicketId, 'ticketType' : TierId }),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmDemoPayment' : IDL.Func(
      [OrderNumber],
      [
        IDL.Variant({
          'ok' : ConfirmPaymentResult,
          'err' : ConfirmPaymentError,
        }),
      ],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, TierId, IDL.Nat],
      [IDL.Variant({ 'ok' : CreateOrderResult, 'err' : CreateOrderError })],
      [],
    ),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvent' : IDL.Func([], [EventInfo], ['query']),
  'getOrder' : IDL.Func([OrderNumber], [IDL.Opt(Order)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listTiers' : IDL.Func([], [IDL.Vec(TicketTier)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'validateTicket' : IDL.Func([SecureToken], [ScanResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderNumber = IDL.Text;
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const TicketStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'valid' : IDL.Null,
    'used' : IDL.Null,
    'refunded' : IDL.Null,
  });
  const EventId = IDL.Text;
  const SecureToken = IDL.Text;
  const TicketId = IDL.Text;
  const TierId = IDL.Text;
  const Ticket = IDL.Record({
    'status' : TicketStatus,
    'eventId' : EventId,
    'secureToken' : SecureToken,
    'ticketId' : TicketId,
    'orderId' : OrderNumber,
    'ticketType' : TierId,
  });
  const ConfirmPaymentResult = IDL.Record({
    'status' : OrderStatus,
    'tickets' : IDL.Vec(Ticket),
    'orderNumber' : OrderNumber,
  });
  const ConfirmPaymentError = IDL.Variant({
    'alreadyPaid' : OrderNumber,
    'unknownOrder' : OrderNumber,
    'orderExpired' : OrderNumber,
  });
  const Rupiah = IDL.Nat;
  const Timestamp = IDL.Int;
  const CreateOrderResult = IDL.Record({
    'total' : Rupiah,
    'paymentDeadline' : Timestamp,
    'serviceFee' : Rupiah,
    'orderNumber' : OrderNumber,
    'subtotal' : Rupiah,
  });
  const CreateOrderError = IDL.Variant({
    'invalidInput' : IDL.Text,
    'unknownTier' : TierId,
    'insufficientStock' : IDL.Record({
      'requested' : IDL.Nat,
      'tierId' : TierId,
      'remaining' : IDL.Nat,
    }),
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const EventInfo = IDL.Record({
    'id' : EventId,
    'timezone' : IDL.Text,
    'venue' : IDL.Text,
    'tagline' : IDL.Text,
    'city' : IDL.Text,
    'date' : IDL.Text,
    'startsAt' : Timestamp,
    'name' : IDL.Text,
    'time' : IDL.Text,
  });
  const CustomerInfo = IDL.Record({
    'whatsapp' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
  });
  const OrderLine = IDL.Record({
    'tierId' : TierId,
    'tierName' : IDL.Text,
    'lineTotal' : Rupiah,
    'quantity' : IDL.Nat,
    'unitPrice' : Rupiah,
  });
  const Order = IDL.Record({
    'status' : OrderStatus,
    'total' : Rupiah,
    'tickets' : IDL.Vec(Ticket),
    'customer' : CustomerInfo,
    'paymentDeadline' : Timestamp,
    'createdAt' : Timestamp,
    'lines' : IDL.Vec(OrderLine),
    'serviceFee' : Rupiah,
    'orderNumber' : OrderNumber,
    'subtotal' : Rupiah,
  });
  const TicketTier = IDL.Record({
    'id' : TierId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'soldOut' : IDL.Bool,
    'remaining' : IDL.Nat,
    'capacity' : IDL.Nat,
    'price' : Rupiah,
  });
  const ScanResult = IDL.Variant({
    'alreadyUsed' : IDL.Record({
      'ticketId' : TicketId,
      'ticketType' : TierId,
    }),
    'invalidTicket' : IDL.Null,
    'validTicket' : IDL.Record({
      'ticketId' : TicketId,
      'ticketType' : TierId,
    }),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmDemoPayment' : IDL.Func(
        [OrderNumber],
        [
          IDL.Variant({
            'ok' : ConfirmPaymentResult,
            'err' : ConfirmPaymentError,
          }),
        ],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, TierId, IDL.Nat],
        [IDL.Variant({ 'ok' : CreateOrderResult, 'err' : CreateOrderError })],
        [],
      ),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvent' : IDL.Func([], [EventInfo], ['query']),
    'getOrder' : IDL.Func([OrderNumber], [IDL.Opt(Order)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listTiers' : IDL.Func([], [IDL.Vec(TicketTier)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'validateTicket' : IDL.Func([SecureToken], [ScanResult], []),
  });
};

export const init = ({ IDL }) => { return []; };