/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export type ConfirmPaymentError = { 'alreadyPaid' : OrderNumber } |
  { 'unknownOrder' : OrderNumber } |
  { 'orderExpired' : OrderNumber };
export interface ConfirmPaymentResult {
  'status' : OrderStatus,
  'tickets' : Array<Ticket>,
  'orderNumber' : OrderNumber,
}
export type CreateOrderError = { 'invalidInput' : string } |
  { 'unknownTier' : TierId } |
  {
    'insufficientStock' : {
      'requested' : bigint,
      'tierId' : TierId,
      'remaining' : bigint,
    }
  };
export interface CreateOrderResult {
  'total' : Rupiah,
  'paymentDeadline' : Timestamp,
  'serviceFee' : Rupiah,
  'orderNumber' : OrderNumber,
  'subtotal' : Rupiah,
}
export interface CustomerInfo {
  'whatsapp' : string,
  'fullName' : string,
  'email' : string,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type EventId = string;
export interface EventInfo {
  'id' : EventId,
  'timezone' : string,
  'venue' : string,
  'tagline' : string,
  'city' : string,
  'date' : string,
  'startsAt' : Timestamp,
  'name' : string,
  'time' : string,
}
export interface Order {
  'status' : OrderStatus,
  'total' : Rupiah,
  'tickets' : Array<Ticket>,
  'customer' : CustomerInfo,
  'paymentDeadline' : Timestamp,
  'createdAt' : Timestamp,
  'lines' : Array<OrderLine>,
  'serviceFee' : Rupiah,
  'orderNumber' : OrderNumber,
  'subtotal' : Rupiah,
}
export interface OrderLine {
  'tierId' : TierId,
  'tierName' : string,
  'lineTotal' : Rupiah,
  'quantity' : bigint,
  'unitPrice' : Rupiah,
}
export type OrderNumber = string;
export type OrderStatus = { 'cancelled' : null } |
  { 'expired' : null } |
  { 'pending' : null } |
  { 'paid' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Rupiah = bigint;
export type ScanResult = {
    'alreadyUsed' : { 'ticketId' : TicketId, 'ticketType' : TierId }
  } |
  { 'invalidTicket' : null } |
  { 'validTicket' : { 'ticketId' : TicketId, 'ticketType' : TierId } };
export type SecureToken = string;
export interface Ticket {
  'status' : TicketStatus,
  'eventId' : EventId,
  'secureToken' : SecureToken,
  'ticketId' : TicketId,
  'orderId' : OrderNumber,
  'ticketType' : TierId,
}
export type TicketId = string;
export type TicketStatus = { 'cancelled' : null } |
  { 'valid' : null } |
  { 'used' : null } |
  { 'refunded' : null };
export interface TicketTier {
  'id' : TierId,
  'name' : string,
  'description' : string,
  'soldOut' : boolean,
  'remaining' : bigint,
  'capacity' : bigint,
  'price' : Rupiah,
}
export type TierId = string;
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Demo payment confirmation — marks the order paid and issues tickets.
   * / Documented as a demo path; the single Midtrans integration point.
   */
  'confirmDemoPayment' : ActorMethod<
    [OrderNumber],
    { 'ok' : ConfirmPaymentResult } |
      { 'err' : ConfirmPaymentError }
  >,
  /**
   * / Create an order from the three checkout fields plus tier and quantity.
   */
  'createOrder' : ActorMethod<
    [string, string, string, TierId, bigint],
    { 'ok' : CreateOrderResult } |
      { 'err' : CreateOrderError }
  >,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Static Markdown description of this backend's public API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / The single hard-coded event.
   */
  'getEvent' : ActorMethod<[], EventInfo>,
  /**
   * / Fetch an order by its order number.
   */
  'getOrder' : ActorMethod<[OrderNumber], [] | [Order]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / All ticket tiers with live remaining stock, read from the actor's
   * / inventory map. `soldOut` is true only when remaining is actually zero.
   */
  'listTiers' : ActorMethod<[], Array<TicketTier>>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Venue scan validation: resolves a scanned secure token to VALID TICKET,
   * / ALREADY USED, or INVALID TICKET, marking the ticket used on first success.
   */
  'validateTicket' : ActorMethod<[SecureToken], ScanResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];