/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Cell {
    value: Value;
    name: string;
}
export type ConfirmPaymentError = {
    __kind__: "alreadyPaid";
    alreadyPaid: OrderNumber;
} | {
    __kind__: "unknownOrder";
    unknownOrder: OrderNumber;
} | {
    __kind__: "orderExpired";
    orderExpired: OrderNumber;
};
export interface ConfirmPaymentResult {
    status: OrderStatus;
    tickets: Array<Ticket>;
    orderNumber: OrderNumber;
}
export type CreateOrderError = {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "unknownTier";
    unknownTier: TierId;
} | {
    __kind__: "insufficientStock";
    insufficientStock: {
        requested: bigint;
        tierId: TierId;
        remaining: bigint;
    };
};
export interface CreateOrderResult {
    total: Rupiah;
    paymentDeadline: Timestamp;
    serviceFee: Rupiah;
    orderNumber: OrderNumber;
    subtotal: Rupiah;
}
export interface CustomerInfo {
    whatsapp: string;
    fullName: string;
    email: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export type EventId = string;
export interface EventInfo {
    id: EventId;
    timezone: string;
    venue: string;
    tagline: string;
    city: string;
    date: string;
    startsAt: Timestamp;
    name: string;
    time: string;
}
export interface Order {
    status: OrderStatus;
    total: Rupiah;
    tickets: Array<Ticket>;
    customer: CustomerInfo;
    paymentDeadline: Timestamp;
    createdAt: Timestamp;
    lines: Array<OrderLine>;
    serviceFee: Rupiah;
    orderNumber: OrderNumber;
    subtotal: Rupiah;
}
export interface OrderLine {
    tierId: TierId;
    tierName: string;
    lineTotal: Rupiah;
    quantity: bigint;
    unitPrice: Rupiah;
}
export type OrderNumber = string;
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type Rupiah = bigint;
export type ScanResult = {
    __kind__: "alreadyUsed";
    alreadyUsed: {
        ticketId: TicketId;
        ticketType: TierId;
    };
} | {
    __kind__: "invalidTicket";
    invalidTicket: null;
} | {
    __kind__: "validTicket";
    validTicket: {
        ticketId: TicketId;
        ticketType: TierId;
    };
};
export type SecureToken = string;
export interface Ticket {
    status: TicketStatus;
    eventId: EventId;
    secureToken: SecureToken;
    ticketId: TicketId;
    orderId: OrderNumber;
    ticketType: TierId;
}
export type TicketId = string;
export interface TicketTier {
    id: TierId;
    name: string;
    description: string;
    soldOut: boolean;
    remaining: bigint;
    capacity: bigint;
    price: Rupiah;
}
export type TierId = string;
export type Timestamp = bigint;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum OrderStatus {
    cancelled = "cancelled",
    expired = "expired",
    pending = "pending",
    paid = "paid"
}
export enum TicketStatus {
    cancelled = "cancelled",
    valid = "valid",
    used = "used",
    refunded = "refunded"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Demo payment confirmation — marks the order paid and issues tickets.
     * / Documented as a demo path; the single Midtrans integration point.
     */
    confirmDemoPayment(orderNumber: OrderNumber): Promise<{
        __kind__: "ok";
        ok: ConfirmPaymentResult;
    } | {
        __kind__: "err";
        err: ConfirmPaymentError;
    }>;
    /**
     * / Create an order from the three checkout fields plus tier and quantity.
     */
    createOrder(fullName: string, email: string, whatsapp: string, tierId: TierId, quantity: bigint): Promise<{
        __kind__: "ok";
        ok: CreateOrderResult;
    } | {
        __kind__: "err";
        err: CreateOrderError;
    }>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Static Markdown description of this backend's public API.
     */
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / The single hard-coded event.
     */
    getEvent(): Promise<EventInfo>;
    /**
     * / Fetch an order by its order number.
     */
    getOrder(orderNumber: OrderNumber): Promise<Order | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / All ticket tiers with live remaining stock, read from the actor's
     * / inventory map. `soldOut` is true only when remaining is actually zero.
     */
    listTiers(): Promise<Array<TicketTier>>;
    schema(): Promise<string>;
    /**
     * / Venue scan validation: resolves a scanned secure token to VALID TICKET,
     * / ALREADY USED, or INVALID TICKET, marking the ticket used on first success.
     */
    validateTicket(token: SecureToken): Promise<ScanResult>;
}
import type { Cell as _Cell, ConfirmPaymentError as _ConfirmPaymentError, ConfirmPaymentResult as _ConfirmPaymentResult, CreateOrderError as _CreateOrderError, CreateOrderResult as _CreateOrderResult, CustomerInfo as _CustomerInfo, Error as _Error, EventId as _EventId, Order as _Order, OrderLine as _OrderLine, OrderNumber as _OrderNumber, OrderStatus as _OrderStatus, Result as _Result, Result__1 as _Result__1, Rupiah as _Rupiah, ScanResult as _ScanResult, SecureToken as _SecureToken, Ticket as _Ticket, TicketId as _TicketId, TicketStatus as _TicketStatus, TierId as _TierId, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async confirmDemoPayment(arg0: OrderNumber): Promise<{
        __kind__: "ok";
        ok: ConfirmPaymentResult;
    } | {
        __kind__: "err";
        err: ConfirmPaymentError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmDemoPayment(arg0);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmDemoPayment(arg0);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrder(arg0: string, arg1: string, arg2: string, arg3: TierId, arg4: bigint): Promise<{
        __kind__: "ok";
        ok: CreateOrderResult;
    } | {
        __kind__: "err";
        err: CreateOrderError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvent(): Promise<EventInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent();
            return result;
        }
    }
    async getOrder(arg0: OrderNumber): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listTiers(): Promise<Array<TicketTier>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTiers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTiers();
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async validateTicket(arg0: SecureToken): Promise<ScanResult> {
        if (this.processError) {
            try {
                const result = await this.actor.validateTicket(arg0);
                return from_candid_ScanResult_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateTicket(arg0);
            return from_candid_ScanResult_n31(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Cell_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ConfirmPaymentError_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConfirmPaymentError): ConfirmPaymentError {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ConfirmPaymentResult_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConfirmPaymentResult): ConfirmPaymentResult {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_CreateOrderError_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateOrderError): CreateOrderError {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return "cancelled" in value ? OrderStatus.cancelled : "expired" in value ? OrderStatus.expired : "pending" in value ? OrderStatus.pending : "paid" in value ? OrderStatus.paid : value;
}
function from_candid_Order_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ScanResult_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScanResult): ScanResult {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_TicketStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketStatus): TicketStatus {
    return "cancelled" in value ? TicketStatus.cancelled : "valid" in value ? TicketStatus.valid : "used" in value ? TicketStatus.used : "refunded" in value ? TicketStatus.refunded : value;
}
function from_candid_Ticket_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ticket): Ticket {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TicketStatus;
    eventId: _EventId;
    secureToken: _SecureToken;
    ticketId: _TicketId;
    orderId: _OrderNumber;
    ticketType: _TierId;
}): {
    status: TicketStatus;
    eventId: EventId;
    secureToken: SecureToken;
    ticketId: TicketId;
    orderId: OrderNumber;
    ticketType: TierId;
} {
    return {
        status: from_candid_TicketStatus_n13(_uploadFile, _downloadFile, value.status),
        eventId: value.eventId,
        secureToken: value.secureToken,
        ticketId: value.ticketId,
        orderId: value.orderId,
        ticketType: value.ticketType
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n21(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n25(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _OrderStatus;
    total: _Rupiah;
    tickets: Array<_Ticket>;
    customer: _CustomerInfo;
    paymentDeadline: _Timestamp;
    createdAt: _Timestamp;
    lines: Array<_OrderLine>;
    serviceFee: _Rupiah;
    orderNumber: _OrderNumber;
    subtotal: _Rupiah;
}): {
    status: OrderStatus;
    total: Rupiah;
    tickets: Array<Ticket>;
    customer: CustomerInfo;
    paymentDeadline: Timestamp;
    createdAt: Timestamp;
    lines: Array<OrderLine>;
    serviceFee: Rupiah;
    orderNumber: OrderNumber;
    subtotal: Rupiah;
} {
    return {
        status: from_candid_OrderStatus_n9(_uploadFile, _downloadFile, value.status),
        total: value.total,
        tickets: from_candid_vec_n10(_uploadFile, _downloadFile, value.tickets),
        customer: value.customer,
        paymentDeadline: value.paymentDeadline,
        createdAt: value.createdAt,
        lines: value.lines,
        serviceFee: value.serviceFee,
        orderNumber: value.orderNumber,
        subtotal: value.subtotal
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _OrderStatus;
    tickets: Array<_Ticket>;
    orderNumber: _OrderNumber;
}): {
    status: OrderStatus;
    tickets: Array<Ticket>;
    orderNumber: OrderNumber;
} {
    return {
        status: from_candid_OrderStatus_n9(_uploadFile, _downloadFile, value.status),
        tickets: from_candid_vec_n10(_uploadFile, _downloadFile, value.tickets),
        orderNumber: value.orderNumber
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    alreadyPaid: _OrderNumber;
} | {
    unknownOrder: _OrderNumber;
} | {
    orderExpired: _OrderNumber;
}): {
    __kind__: "alreadyPaid";
    alreadyPaid: OrderNumber;
} | {
    __kind__: "unknownOrder";
    unknownOrder: OrderNumber;
} | {
    __kind__: "orderExpired";
    orderExpired: OrderNumber;
} {
    return "alreadyPaid" in value ? {
        __kind__: "alreadyPaid",
        alreadyPaid: value.alreadyPaid
    } : "unknownOrder" in value ? {
        __kind__: "unknownOrder",
        unknownOrder: value.unknownOrder
    } : "orderExpired" in value ? {
        __kind__: "orderExpired",
        orderExpired: value.orderExpired
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CreateOrderResult;
} | {
    err: _CreateOrderError;
}): {
    __kind__: "ok";
    ok: CreateOrderResult;
} | {
    __kind__: "err";
    err: CreateOrderError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_CreateOrderError_n17(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    invalidInput: string;
} | {
    unknownTier: _TierId;
} | {
    insufficientStock: {
        requested: bigint;
        tierId: _TierId;
        remaining: bigint;
    };
}): {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "unknownTier";
    unknownTier: TierId;
} | {
    __kind__: "insufficientStock";
    insufficientStock: {
        requested: bigint;
        tierId: TierId;
        remaining: bigint;
    };
} {
    return "invalidInput" in value ? {
        __kind__: "invalidInput",
        invalidInput: value.invalidInput
    } : "unknownTier" in value ? {
        __kind__: "unknownTier",
        unknownTier: value.unknownTier
    } : "insufficientStock" in value ? {
        __kind__: "insufficientStock",
        insufficientStock: value.insufficientStock
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    alreadyUsed: {
        ticketId: _TicketId;
        ticketType: _TierId;
    };
} | {
    invalidTicket: null;
} | {
    validTicket: {
        ticketId: _TicketId;
        ticketType: _TierId;
    };
}): {
    __kind__: "alreadyUsed";
    alreadyUsed: {
        ticketId: TicketId;
        ticketType: TierId;
    };
} | {
    __kind__: "invalidTicket";
    invalidTicket: null;
} | {
    __kind__: "validTicket";
    validTicket: {
        ticketId: TicketId;
        ticketType: TierId;
    };
} {
    return "alreadyUsed" in value ? {
        __kind__: "alreadyUsed",
        alreadyUsed: value.alreadyUsed
    } : "invalidTicket" in value ? {
        __kind__: "invalidTicket",
        invalidTicket: value.invalidTicket
    } : "validTicket" in value ? {
        __kind__: "validTicket",
        validTicket: value.validTicket
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ConfirmPaymentResult;
} | {
    err: _ConfirmPaymentError;
}): {
    __kind__: "ok";
    ok: ConfirmPaymentResult;
} | {
    __kind__: "err";
    err: ConfirmPaymentError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ConfirmPaymentResult_n7(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ConfirmPaymentError_n14(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ticket>): Array<Ticket> {
    return value.map((x)=>from_candid_Ticket_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n23(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
